### PR TITLE
Control the flow of the authentication state so the failure handler can know what the problem was

### PR DESCRIPTION
**Pull request by brunoais**
This is a PR for #61 for evaluation.
This code is already feature-complete although I didn't check if this is the most efficient way of solving the problem at hand.
I didn't benchmark this specific code, although I've done benchmarking of short code samples to confirm execution speeds and timers.

Feel free to point out failures or places where I didn't solve the current problem in a good way for your project

If all looks good for you, I'll write the automated tests for this.

### CODE REVIEW

**Comment by brunoais** [comment]
> I definitely do not think using automatic dependency injection for the error handler is a good idea. You are basically forcing users to use the argument names that you picked, which might be an accepted practice for Angular, but in Python is extremely unusual, at least in my opinion.

OK. Positional arguments, then?

>Also the logic that you added to determine the status code executes even if the error handler does not want the extra arguments, so for the general case the effort to determine the cause of the error is spent, only to then throw away the result when the error handler is invoked.

Although that is true, the work done to find that is, computing-wise, minimal and negligible. It is made of very few amount of `if` statements and assignments. The only exception being the exception which is a very rare event. I only used an exception because I was unable to find a fitting replacement.

> maybe even better as an optional extension?

I can do as an extension but I'd need your support to develop such extension without redoing most of the code you have already done.... Or do you mean wrapper code?
If so, are you able to give support to it?

**Comment by miguelgrinberg** [comment]
> I can do as an extension but I'd need your support to develop such extension without redoing most of the code you have already done.... Or do you mean wrapper code?

The logic to determine the cause of the failure is just a handful of lines of code. It could easily be provided in your wrapper extension as a customized error handler, without additional support (since you can access the `Authorization` header from `request.headers`). While there would be some simple logic from Flask-HTTPAuth duplicated, this makes sense to me, because in that way the additional effort to determine the failure cause is only made when an error has been found and the caller is interested in that information, but not in any other case.

**Comment by brunoais** [comment]
The situation I'm stuck in doesn't give me that choice, even how reasonable it seems. I already had to replace my own code (all implemented) with this lib... This lib is good, just that it doesn't tell what is wrong, when it is wrong, while my code did. I thought the extra logic was very light with all the choices I did to lighten it up. I'll work on finding a solution

**Comment by miguelgrinberg** [comment]
Honestly I don't understand. What I'm saying is that you can implement the detection logic in your error handler. You don't even need an extension wrapper for that, just add the logic to find the cause at the beginning of your error handler function.

**Comment by brunoais** [comment]
I see. Thanks.

**Pull request closed without merging**
